version: '3'

services:
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports:
          - 5432:5432
    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]
    pgadmin4:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: anthony.margerand@protonmail.com
            PGADMIN_DEFAULT_PASSWORD: 123
        ports:
          - 5050:80
